# Generated by Django 2.1.5 on 2022-01-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20220102_1216'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('catalog.can_read_all_borrowed', 'Only staff can read all borrowed books'),)},
        ),
    ]
